name: main
on:
  push:
    branches:
      - main
jobs:
  release:
    container:
      image: node:20
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache local downloads
        uses: actions/cache@v4
        with:
          path: /github/home/.npm
          key: ${{ runner.os }}-npm-packages
      - name: Install buildtime dependencies
        run: npm ci
      - name: Lint
        run: npx eslint
      - name: Test
        run: npm test
      - name: Compile
        run: npm run build
      - name: Package
        run: |
          tar \
              -C ./build \
              -c \
              -f release.tar \
              .
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./release.tar
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
