name: main
on:
  pull_request:
    branches:
      - $default-branch
  push: 
    branches:
      - $default-branch
jobs:
  buildAndUpload:
    container:
      image: node:20
    defaults:
      run:
        working-directory: /root
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache local downloads
        uses: actions/cache@v4
        with:
          path: /github/home/.npm
          key: ${{ runner.os }}-npm-packages
      - name: Install buildtime dependencies
        run: npm ci
      - name: Compile
        run: npm build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build_outputs_folder/
  deploy:
    container:
      image: node:20
    defaults:
      run:
        working-directory: /root
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: buildAndUpload
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
